updating FrontEnd reading env file

diff --git a/295topics-fullstack/Dockerfile.fe b/295topics-fullstack/Dockerfile.fe
--- a/295topics-fullstack/Dockerfile.fe
+++ b/295topics-fullstack/Dockerfile.fe
@@ -9,10 +9,14 @@ RUN apk add bash
 RUN apk add curl
 
 RUN yarn install --frozen-lockfile
+RUN yarn add dotenv
 
 COPY ./frontend/ .
 RUN echo "API_URI=http://295fsbe:5000/api/topics" > .env
 RUN echo " " > .env
-ENV API_URI http://295fsbe:5000/api/topics
 
-CMD ["node", "server.js"]
+sed -i '/"test": "echo\"Error: no test specified\" && exit 1"/a\ "start:with-env": "node -r dotenv\/config server.js"' package.json
+
+EXPOSE 3000
+
+CMD ["yarn", "run", "start:with-env"]
